// KI Automation Hub — Impact Page Styles
// Kaplan International

import { makeStyles, shorthands, tokens } from '@fluentui/react-components';

export const useImpactStyles = makeStyles({
  root: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('24px'),
    ...shorthands.padding('24px'),
    maxWidth: '1100px',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  pageHeader: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('6px'),
    marginBottom: '8px',
  },
  pageTitle: {
    color: '#003087',
    fontWeight: '800',
    letterSpacing: '-0.02em',
  },
  pageSubtitle: {
    color: '#8a99b5',
    fontSize: tokens.fontSizeBase300,
  },
  heroStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    ...shorthands.gap('16px'),
  },
  statCard: {
    backgroundColor: tokens.colorNeutralBackground1,
    ...shorthands.borderRadius('12px'),
    ...shorthands.padding('20px'),
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('8px'),
    boxShadow: '0 1px 4px rgba(0,48,135,0.08)',
    ...shorthands.border('1px', 'solid', '#e8ecf4'),
  },
  statCardHighlight: {
    backgroundColor: '#003087',
    ...shorthands.borderRadius('12px'),
    ...shorthands.padding('20px'),
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('8px'),
    boxShadow: '0 4px 16px rgba(0,48,135,0.25)',
  },
  statLabel: {
    color: '#8a99b5',
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  statLabelLight: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  statValue: {
    color: '#003087',
    fontSize: '2rem',
    fontWeight: '800',
    lineHeight: '1',
    letterSpacing: '-0.03em',
  },
  statValueLight: {
    color: '#ffffff',
    fontSize: '2rem',
    fontWeight: '800',
    lineHeight: '1',
    letterSpacing: '-0.03em',
  },
  statSubtext: {
    color: '#8a99b5',
    fontSize: tokens.fontSizeBase200,
  },
  statSubtextLight: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: tokens.fontSizeBase200,
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('16px'),
  },
  sectionTitle: {
    color: '#003087',
    fontWeight: tokens.fontWeightSemibold,
    fontSize: tokens.fontSizeBase400,
  },
  trendCard: {
    backgroundColor: tokens.colorNeutralBackground1,
    ...shorthands.borderRadius('12px'),
    ...shorthands.padding('24px'),
    ...shorthands.border('1px', 'solid', '#e8ecf4'),
    boxShadow: '0 1px 4px rgba(0,48,135,0.08)',
  },
  barChart: {
    display: 'flex',
    alignItems: 'flex-end',
    ...shorthands.gap('8px'),
    height: '120px',
    marginTop: '16px',
  },
  barWrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    ...shorthands.gap('4px'),
    flex: '1',
  },
  bar: {
    width: '100%',
    backgroundColor: '#0057c8',
    ...shorthands.borderRadius('4px', '4px', '0', '0'),
    minHeight: '4px',
  },
  barCurrent: {
    backgroundColor: '#003087',
  },
  barLabel: {
    fontSize: tokens.fontSizeBase100,
    color: '#8a99b5',
    textAlign: 'center',
  },
  barValue: {
    fontSize: tokens.fontSizeBase100,
    color: '#3d4a6b',
    fontWeight: tokens.fontWeightSemibold,
  },
  topAutomationCard: {
    backgroundColor: tokens.colorNeutralBackground1,
    ...shorthands.borderRadius('12px'),
    ...shorthands.padding('20px'),
    ...shorthands.border('1px', 'solid', '#e8ecf4'),
    boxShadow: '0 1px 4px rgba(0,48,135,0.08)',
    display: 'flex',
    alignItems: 'center',
    ...shorthands.gap('16px'),
  },
  topAutomationIcon: {
    width: '48px',
    height: '48px',
    backgroundColor: '#e8ecf4',
    ...shorthands.borderRadius('12px'),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '24px',
    flexShrink: '0',
  },
  topAutomationInfo: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('4px'),
  },
  topAutomationName: {
    color: '#003087',
    fontWeight: tokens.fontWeightSemibold,
    fontSize: tokens.fontSizeBase400,
  },
  topAutomationStats: {
    color: '#8a99b5',
    fontSize: tokens.fontSizeBase200,
  },
  projectionBanner: {
    backgroundColor: '#003087',
    ...shorthands.borderRadius('12px'),
    ...shorthands.padding('24px'),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...shorthands.gap('16px'),
  },
  projectionText: {
    display: 'flex',
    flexDirection: 'column',
    ...shorthands.gap('6px'),
  },
  projectionTitle: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: tokens.fontSizeBase500,
  },
  projectionSubtitle: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: tokens.fontSizeBase300,
  },
  projectionStat: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  projectionValue: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: '2.5rem',
    letterSpacing: '-0.03em',
    lineHeight: '1',
  },
  projectionLabel: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: tokens.fontSizeBase200,
  },
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '200px',
  },
  disclaimer: {
    color: '#8a99b5',
    fontSize: tokens.fontSizeBase100,
    textAlign: 'center',
    ...shorthands.padding('0', '0', '16px'),
  },
});
